// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	TokenHash    string             `json:"token_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	ReplacedByID pgtype.UUID        `json:"replaced_by_id"`
	UserAgent    *string            `json:"user_agent"`
	Ip           *netip.Addr        `json:"ip"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	AvatarUrl    *string            `json:"avatar_url"`
	Phone        string             `json:"phone"`
	CreatedDate  pgtype.Timestamptz `json:"created_date"`
	UpdatedDate  pgtype.Timestamptz `json:"updated_date"`
}
