// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) (int64, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenByID(ctx context.Context, id pgtype.UUID) (RefreshToken, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) (int64, error)
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) (RefreshToken, error)
	RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (RefreshToken, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UsernameExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
